source 'https://rubygems.org'
ruby '2.1.5'
gem 'jekyll', '~> 2.5.0'
gem 'jekyll-sitemap', '~> 0.5'
gem 'jekyll-paginate-by', github: 'marighella/jekyll-paginate-by'
gem 'neat'
gem 'httparty'
gem 'slugify'
gem 'sass'
