source 'https://rubygems.org'
ruby '2.1.5'
gem 'jekyll', '~> 2.5.0'
gem 'jekyll-sitemap', '~> 0.5'
#gem 'jekyll-paginate', path: '../jekyll-paginate'
gem 'jekyll-paginate', github: 'marighella/jekyll-paginate'
gem 'neat'
gem 'httparty'
