#!/bin/bash

function abort {
  echo >&2 "setup failed."; exit 1;
}

function check_installation {
  hash $1 2>/dev/null || { echo >&2 "ERROR: $1 is not available."; abort; }
}

function check_ruby {
  check_installation ruby
  ruby -v | grep -q "ruby 2" || {
    echo >&2 "you need ruby version >= 2."; abort;
  }
  echo "✓ ruby is ok."
}

function check_mysql {
  check_installation mysql
  mysql --version | grep -q "Distrib 5" || {
    echo >&2 "you need mysql version >= 5."; abort;
  }
  echo "✓ mysql is ok."
}

function check_mysqld {
  if [ ! -h /var/mysql/mysql.sock ]; then
    ln -s /var/mysql/mysql.sock /tmp/mysql.sock && chmod 755 /tmp/mysql.sock
  fi

  mysqladmin ping | grep -q "mysqld is alive" || {
    echo >&2 "mysqld is not currently running."; abort;
  }
  echo "✓ mysqld is running"
}

function restore_database {
  echo "restoring the database..."
  curl "https://dl.dropboxusercontent.com/u/83384696/mst2.sql.gz" > mst2.sql.gz || abort
  gzip -d mst2.sql.gz

  drop_db="drop database if exists mst2;"
  create_db="create database mst2;"
  increase_mem="set global max_allowed_packet=1073741824;"
  use_db="use mst2;"

  (( echo "$drop_db $create_db $increase_mem $use_db" && cat mst2.sql ) | mysql -u root -p  ) || abort

  rm mst2.sql
  echo "✓ database restored."
}

function install_gems {
  echo "installing gems..."
  (gem install bundler >/dev/null && bundle install) || abort 
  echo "✓ gems installed."
}

echo "setting up movimento-sem-terra/site-novo..."
check_ruby
check_node
check_mysql
check_mysqld
install_gems
restore_database
echo "setup is complete!"

